In [9]:
import numpy as np
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
X=np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y=np.array([[0],[1],[1],[0]])
np.random.seed(1)
syn0=2*np.random.random((3,4))-1
syn1=2*np.random.random((4,1))-1
print(syn0)
print(syn1)
for j in range(60000):
    l0=X
    l1=nonlin(np.dot(l0,syn0))
    l2=nonlin(np.dot(l1,syn1))
    l2_error=y-l2
    if(j%10000)==0:
        print("error"+str(np.mean(np.abs(l2_error))))
        
    l2_delta=l2_error*nonlin(l2,deriv=True)
    l1_error=l2_delta.dot(syn1.T)
    l1_delta=l1_error*nonlin(l1,deriv=True)
    
    syn1+=l1.T.dot(l2_delta)
    syn0+=l0.T.dot(l1_delta)

print("Output after training")
print(l2)

[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
error0.4964100319027255
error0.008584525653247157
error0.005789459862507806
error0.004629176776769983
error0.003958765280273646
error0.0035101225678616736
Output after training
[[0.00260572]
 [0.99672209]
 [0.99701711]
 [0.00386759]]


In [ ]:
np.random.seed(1)
print(2*np.random.random((3,4))-1)
np.random.random((3,4))

In [4]:
l2=np.dot(X,syn0)

In [9]:
l2_error=y-l2
l2_error

array([[-0.97538679,  2.02685775, -2.52949751, -5.84371739],
       [ 2.60874805,  8.84133705,  5.07843684, -1.15975616],
       [-4.57674389, -1.14511418,  4.78006494, -0.64626622],
       [-2.99260905,  3.66936512, 10.3879993 ,  2.03769501]])

In [10]:
l2*(1-l2)

array([[ 2.40074018e-02, -6.13501010e+00, -3.86886014e+00,
        -2.83053156e+01],
       [-4.19681833e+00, -6.93279037e+01, -2.07120839e+01,
        -2.50479052e+00],
       [-2.55233285e+01, -2.45640065e+00, -1.80689559e+01,
        -1.06392624e+00],
       [-5.96309988e+00, -1.71336055e+01, -1.18298529e+02,
        -6.18989598e+00]])

In [17]:
l2_error*(l2*(1-l2))

array([[-2.34165026e-02, -1.24347928e+01,  9.78627209e+00,
         1.65408265e+02],
       [-1.09484416e+01, -6.12951363e+02, -1.05185010e+02,
         2.90494623e+00],
       [ 1.16813738e+02,  2.81285921e+00, -8.63707827e+01,
         6.87579591e-01],
       [ 1.78452267e+01, -6.28694542e+01, -1.22888503e+03,
        -1.26131202e+01]])

In [6]:
X.T

array([[0, 0, 1, 1],
       [0, 1, 0, 1],
       [1, 1, 1, 1]])