## First Method

In [1]:
import numpy as np
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
X=np.array([[1,0,0,0,1],[1,0,0,1,1],[1,0,1,0,1],[1,0,1,1,1],[1,1,0,0,1],[1,1,0,1,1],[1,1,1,0,1],[1,1,1,1,1]])
y=np.array([[0],[1],[1],[1],[1],[1],[1],[1]])
np.random.seed(1)
syn0=2*np.random.random((5,8))-1
syn1=2*np.random.random((8,1))-1
print(syn0)
print(syn1)
for j in range(60000):
    l0=X
    l1=nonlin(np.dot(l0,syn0))
    l2=nonlin(np.dot(l1,syn1))
    l2_error=y-l2
    if(j%10000)==0:
        print("error"+str(np.mean(np.abs(l2_error))))
        
    l2_delta=l2_error*nonlin(l2,deriv=True)
    l1_error=l2_delta.dot(syn1.T)
    l1_delta=l1_error*nonlin(l1,deriv=True)
    
    syn1+=l1.T.dot(l2_delta)
    syn0+=l0.T.dot(l1_delta)

print("Output after training")
print(l2)
print(syn1)
print(syn0)

[[-0.16595599  0.44064899 -0.99977125 -0.39533485 -0.70648822 -0.81532281
  -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439   -0.5910955   0.75623487
  -0.94522481  0.34093502]
 [-0.1653904   0.11737966 -0.71922612 -0.60379702  0.60148914  0.93652315
  -0.37315164  0.38464523]
 [ 0.7527783   0.78921333 -0.82991158 -0.92189043 -0.66033916  0.75628501
  -0.80330633 -0.15778475]
 [ 0.91577906  0.06633057  0.38375423 -0.36896874  0.37300186  0.66925134
  -0.96342345  0.50028863]]
[[ 0.97772218]
 [ 0.49633131]
 [-0.43911202]
 [ 0.57855866]
 [-0.79354799]
 [-0.10421295]
 [ 0.81719101]
 [-0.4127717 ]]
error0.3990070740353202
error0.002456785814652322
error0.0016749535968706485
error0.0013423152363943166
error0.0011483085207945939
error0.0010178505844630785
Output after training
[[0.0027746 ]
 [0.99850342]
 [0.99847255]
 [0.99998562]
 [0.99847056]
 [0.99998568]
 [0.9999842 ]
 [0.99999166]]
[[ 3.67779277]
 [ 3.5197633 ]
 [-5.54444532]
 [-0.02457629]
 [-4.9229302 ]
 [ 4.

## Second Method

In [6]:
import pandas as pd
import sys
import numpy as np
import warnings
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
warnings.filterwarnings("ignore")
plt.style.use("seaborn-talk")
%matplotlib notebook

def sigmoid(x):
    return 1/(1+np.exp(-x))
def hypothysis(x,w):
    return np.dot(x,w)
def error_function(y,y_cap):
    error=((-y*np.log(y_cap)-(1-y)*np.log(1-y_cap))**2).mean()
    return error
def gradient_decent(x,y,y_cap,alpha=0.2):
    return alpha*(x.T@(y_cap - y).T/len(y))
def calculate_weight(x,y,weight=np.array([1,1,1])):
    for z in np.arange(1,0.00001,-0.0001):
        Y=hypothysis(x,weight)
        y_cap=sigmoid(Y)
        error=error_function(y,y_cap)
        weight=weight - gradient_decent(x,y,y_cap,z)
    return weight,error


In [11]:
INPUT=X=np.array([[1,1,0,0,0],[1,1,0,0,1],[1,1,0,1,0],[1,1,0,1,1],[1,1,1,0,0],[1,1,1,0,1],[1,1,1,1,0],[1,1,1,1,1]])

OR=np.array([0,1,1,1,1,1,1,1])
OR_weight,error=calculate_weight(INPUT,OR,np.array([0,0,0,0,0]))
print("Weight",OR_weight)
print("Error",error)

Weight [-2.27050917 -2.27050917 10.26838236 10.26838236 10.26838236]
Error 1.802298150095122e-05


In [12]:
y_cap=sigmoid(np.dot(INPUT,OR_weight))

In [13]:
y_cap

array([0.01055005, 0.99675492, 0.99675492, 0.99999989, 0.99675492,
       0.99999989, 0.99999989, 1.        ])